#!/usr/bin/env python3
"""MCP server for buildbot — dependency-free stdio JSON-RPC 2.0.

Auto-generated by the TRL/MCP rollout. Speaks the Model Context Protocol
(`tools` capability) over stdio so agentic clients can drive this application.

Tools are built from mcp-server/server_config.json:
  - app_info                     always
  - run_cli                      when the app has a CLI entry point
  - <method>_<path>              one per discovered HTTP route (if any)
  - list_pages / get_page / search   for static sites

Run:  python3 mcp-server/mcp_server.py
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import urllib.error
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
REPO_ROOT = os.path.dirname(HERE)
SERVER_NAME = "buildbot-mcp"
SERVER_VERSION = "1.0.0"
PROTOCOL_VERSION = "2024-11-05"
CLI_TIMEOUT = 180

if REPO_ROOT not in sys.path:
    sys.path.insert(0, REPO_ROOT)


def _load_config():
    with open(os.path.join(HERE, "server_config.json"), encoding="utf-8") as fh:
        return json.load(fh)


CONFIG = _load_config()
APP = CONFIG.get("app", {})
STACK = CONFIG.get("stack", "python")


def _schema(properties=None, required=None):
    return {"type": "object", "properties": properties or {}, "required": required or [],
            "additionalProperties": False}


def _str(desc):
    return {"type": "string", "description": desc}


ROUTES = CONFIG.get("routes", [])
PAGES = CONFIG.get("pages", [])
MODULE = CONFIG.get("module")
BASE_URL = os.environ.get("MCP_APP_BASE_URL", CONFIG.get("base_url", "http://localhost:8000"))


def _run(cmd):
    try:
        proc = subprocess.run(cmd, cwd=REPO_ROOT, capture_output=True, text=True, timeout=CLI_TIMEOUT)
    except subprocess.TimeoutExpired:
        return f"command timed out after {CLI_TIMEOUT}s"
    text = (proc.stdout or "").strip()
    err = (proc.stderr or "").strip()
    if proc.returncode != 0:
        return (text + ("\n" if text and err else "") + err).strip() or f"exit code {proc.returncode}"
    return text or "(no output)"


def _app_info(_args):
    return json.dumps({"name": APP.get("name", SERVER_NAME), "version": APP.get("version", "unknown"),
                       "description": APP.get("description", ""), "stack": STACK,
                       "repo_root": REPO_ROOT,
                       "mcp_server": {"name": SERVER_NAME, "version": SERVER_VERSION,
                                      "protocol": PROTOCOL_VERSION},
                       "tools": sorted(TOOLS)}, indent=2)


def _run_cli(args):
    argv = args.get("args") or []
    if not isinstance(argv, list):
        raise ValueError("`args` must be an array of strings")
    return _run([sys.executable, "-m", MODULE] + [str(x) for x in argv]) if MODULE else "(no CLI entry)"


def _route_tool(route):
    path = route["path"]
    method = route["method"].upper()

    def call(args):
        url = BASE_URL.rstrip("/") + path
        for part in path.split("/"):
            if part.startswith("{") and part.endswith("}"):
                key = part[1:-1]
                url = url.replace(part, str(args.get(key, "")))
        body = None
        if method in ("POST", "PUT", "PATCH") and "body" in args:
            body = json.dumps(args["body"]).encode()
        query = args.get("query")
        if query:
            from urllib.parse import urlencode
            url += ("&" if "?" in url else "?") + urlencode(query)
        req = urllib.request.Request(url, data=body, method=method)
        req.add_header("Content-Type", "application/json")
        try:
            with urllib.request.urlopen(req, timeout=CLI_TIMEOUT) as resp:
                return resp.read().decode("utf-8", "replace")
        except urllib.error.HTTPError as exc:
            return f"HTTP {exc.code}: {exc.read().decode('utf-8', 'replace')}"
        except Exception as exc:
            return f"{type(exc).__name__}: {exc}"

    return call


def _list_pages(_args):
    return json.dumps(sorted(PAGES), indent=2)


def _get_page(args):
    name = str(args.get("page", ""))
    match = next((p for p in PAGES if p == name or p.lower() == name.lower()), None)
    if not match:
        raise ValueError(f"unknown page: {name}")
    with open(os.path.join(REPO_ROOT, match), encoding="utf-8", errors="replace") as fh:
        return fh.read()


def _search(args):
    needle = str(args.get("query", "")).lower()
    if not needle:
        raise ValueError("query is required")
    hits = []
    for page in PAGES:
        try:
            with open(os.path.join(REPO_ROOT, page), encoding="utf-8", errors="replace") as fh:
                text = fh.read()
        except OSError:
            continue
        for i, line in enumerate(text.splitlines(), 1):
            if needle in line.lower():
                hits.append(f"{page}:{i}: {line.strip()[:200]}")
    return "\n".join(hits[:200]) or "(no matches)"


def build_tools():
    tools = {"app_info": {"description": "Metadata about this application and its MCP server.",
                          "inputSchema": _schema(), "call": _app_info}}
    if MODULE:
        tools["run_cli"] = {
            "description": "Run the application CLI. `args` is an array of string arguments.",
            "inputSchema": _schema({"args": {"type": "array", "items": {"type": "string"},
                                             "description": "CLI arguments."}}),
            "call": _run_cli,
        }
    for route in ROUTES:
        safe = "".join(c if c.isalnum() else "_" for c in f"{route['method']}_{route['path']}").strip("_").lower()
        params = {}
        required = []
        for part in route["path"].split("/"):
            if part.startswith("{") and part.endswith("}"):
                key = part[1:-1]
                params[key] = _str(f"Path parameter `{key}`.")
                required.append(key)
        if route["method"].upper() in ("POST", "PUT", "PATCH"):
            params["body"] = {"type": "object", "description": "JSON request body."}
        params["query"] = {"type": "object", "description": "Query string parameters."}
        tools[f"http_{safe}"] = {
            "description": f"{route['method'].upper()} {route['path']}",
            "inputSchema": _schema(params, required),
            "call": _route_tool(route),
        }
    if PAGES:
        tools["list_pages"] = {"description": "List the site's HTML pages.",
                               "inputSchema": _schema(), "call": _list_pages}
        tools["get_page"] = {"description": "Return a page's HTML source.",
                             "inputSchema": _schema({"page": _str("Page path.")}, ["page"]),
                             "call": _get_page}
        tools["search_content"] = {"description": "Search across site pages for a string.",
                                   "inputSchema": _schema({"query": _str("Text to find.")}, ["query"]),
                                   "call": _search}
    return tools


TOOLS = build_tools()


def handle(request):
    method = request.get("method")
    req_id = request.get("id")
    if method == "initialize":
        result = {"protocolVersion": PROTOCOL_VERSION,
                  "capabilities": {"tools": {"listChanged": False}},
                  "serverInfo": {"name": SERVER_NAME, "version": SERVER_VERSION}}
    elif method in ("notifications/initialized", "initialized", "notifications/cancelled"):
        return None
    elif method == "ping":
        result = {}
    elif method == "tools/list":
        result = {"tools": [{"name": n, "description": t["description"], "inputSchema": t["inputSchema"]}
                            for n, t in TOOLS.items()]}
    elif method == "tools/call":
        params = request.get("params") or {}
        name = params.get("name")
        spec = TOOLS.get(name)
        if spec is None:
            result = _error_result(f"Unknown tool: {name}")
        else:
            try:
                result = {"content": [{"type": "text", "text": spec["call"](params.get("arguments") or {})}],
                          "isError": False}
            except Exception as exc:
                result = _error_result(f"{type(exc).__name__}: {exc}")
    elif method == "resources/list":
        result = {"resources": []}
    elif method == "prompts/list":
        result = {"prompts": []}
    else:
        if req_id is None:
            return None
        return {"jsonrpc": "2.0", "id": req_id,
                "error": {"code": -32601, "message": f"Method not found: {method}"}}
    if req_id is None:
        return None
    return {"jsonrpc": "2.0", "id": req_id, "result": result}


def _error_result(msg):
    return {"content": [{"type": "text", "text": msg}], "isError": True}


def main():
    for line in sys.stdin:
        line = line.strip()
        if not line:
            continue
        try:
            request = json.loads(line)
        except json.JSONDecodeError as exc:
            sys.stdout.write(json.dumps({"jsonrpc": "2.0", "id": None,
                                         "error": {"code": -32700, "message": str(exc)}}) + "\n")
            sys.stdout.flush()
            continue
        response = handle(request)
        if response is not None:
            sys.stdout.write(json.dumps(response) + "\n")
            sys.stdout.flush()


if __name__ == "__main__":
    main()
