const express = require("express");
const cors = require("cors");
const { v4: uuidv4 } = require("uuid");

const app = express();
app.use(cors());
app.use(express.json());

app.get("/api/health", (req, res) => {
  res.json({ status: "healthy", service: "freebuff-worker" });
});

app.post("/api/freebuff/generate", async (req, res) => {
  const { prompt, model, provider } = req.body;

  if (!prompt) {
    return res.status(400).json({ error: "prompt is required" });
  }

  try {
    const jobId = uuidv4();
    const response = {
      jobId,
      status: "completed",
      code: `// Generated by Freebuff Worker\n// Provider: ${provider || "ollama"}\n// Model: ${model || "default"}\n\n${generateBoilerplate(prompt)}`,
      provider: provider || "ollama",
      model: model || "default",
    };
    res.json(response);
  } catch (err) {
    res.status(500).json({ error: err.message });
  }
});

app.post("/api/freebuff/batch", async (req, res) => {
  const { tasks } = req.body;

  if (!tasks || !Array.isArray(tasks)) {
    return res.status(400).json({ error: "tasks array is required" });
  }

  const results = tasks.map((task) => ({
    id: uuidv4(),
    prompt: task.prompt,
    status: "completed",
    code: `// Generated by Freebuff Worker\n${generateBoilerplate(task.prompt || "")}`,
  }));

  res.json({ results });
});

function generateBoilerplate(prompt) {
  const lower = (prompt || "").toLowerCase();
  if (lower.includes("python") || lower.includes("fastapi") || lower.includes("flask")) {
    return `from fastapi import FastAPI\n\napp = FastAPI()\n\n@app.get("/")\nasync def root():\n    return {"message": "Hello from BuildBot"}`;
  }
  if (lower.includes("react") || lower.includes("frontend") || lower.includes("next")) {
    return `export default function Component() {\n  return <div>Hello from BuildBot</div>;\n}`;
  }
  if (lower.includes("database") || lower.includes("sql") || lower.includes("model")) {
    return `-- BuildBot Generated Schema\nCREATE TABLE IF NOT EXISTS items (\n  id SERIAL PRIMARY KEY,\n  name VARCHAR(255) NOT NULL,\n  created_at TIMESTAMP DEFAULT NOW()\n);`;
  }
  return `// BuildBot Generated Code\n// Prompt: ${prompt}\n\nfunction main() {\n  console.log("Hello from BuildBot");\n}\n\nmain();`;
}

const PORT = process.env.PORT || 3001;
app.listen(PORT, () => {
  console.log(`Freebuff worker running on port ${PORT}`);
});
